###
GET  http://localhost:3000/post/626402b2d0fb472e5367b166

###

POST  http://localhost:3000/post
Content-Type:application/json

{
    "message":"first message",
    "sender": "kfir2"

}
###

GET http://localhost:3000/post
###

GET http://localhost:3000/post?sender=kfir